on:
  push:
    branches: [ master ]
  workflow_dispatch:
name: Build and push to Docker Hub
  
jobs:
  deploy:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get 10 digits GITHUB_SHA
      id: image-tag
      run: |
         echo ::set-output name=tag::$(git rev-parse --short=10 ${{ github.sha }})

    - name: Build jar
      run: |
        ./gradlew :electronic-bill-application:bootJar

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
    - name: Build, tag, and push image to Docker Hub
      id: build-image
      env:
        IMAGE_TAG: ${{ steps.image-tag.outputs.tag }}
      run: |
        docker build -t dinastiainc/electronic-bill-api .
        docker tag dinastiainc/electronic-bill-api:latest dinastiainc/electronic-bill-api:$IMAGE_TAG
        docker push dinastiainc/electronic-bill-api:$IMAGE_TAG
        docker push dinastiainc/electronic-bill-api
